create table if not exists public.school_plans (
  code text primary key,
  name text not null,
  plan_type text not null,

  monthly_price_cents integer,
  currency text not null default 'ZAR',

  min_schools integer,
  max_schools integer,

  max_teachers integer,
  max_learners integer,

  report_history_months integer,

  whatsapp_delivery boolean not null default false,
  photo_moments boolean not null default false,
  video_moments boolean not null default false,
  awards boolean not null default false,
  try_at_home boolean not null default false,
  reaction_tracking boolean not null default false,

  full_report_history boolean not null default false,
  priority_support boolean not null default false,
  white_label boolean not null default false,
  custom_onboarding boolean not null default false,

  central_group_dashboard boolean not null default false,
  cross_branch_reporting boolean not null default false,
  group_announcements boolean not null default false,
  dedicated_onboarding boolean not null default false,
  custom_domain boolean not null default false,
  dedicated_account_manager boolean not null default false,
  monthly_check_in boolean not null default false,
  early_access boolean not null default false,

  is_active boolean not null default true,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint school_plans_type_check
    check (
      plan_type in (
        'single',
        'group',
        'enterprise'
      )
    ),

  constraint school_plans_price_check
    check (
      monthly_price_cents is null
      or monthly_price_cents >= 0
    )
);

insert into public.school_plans (
  code,
  name,
  plan_type,
  monthly_price_cents,
  min_schools,
  max_schools,
  max_teachers,
  max_learners,
  report_history_months,
  whatsapp_delivery,
  photo_moments,
  video_moments,
  awards,
  try_at_home,
  reaction_tracking,
  full_report_history,
  priority_support,
  white_label,
  custom_onboarding,
  central_group_dashboard,
  cross_branch_reporting,
  group_announcements,
  dedicated_onboarding,
  custom_domain,
  dedicated_account_manager,
  monthly_check_in,
  early_access
)
values

(
  'starter',
  'Starter',
  'single',
  0,
  1,
  1,
  1,
  20,
  0,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false
),

(
  'pro',
  'Pro',
  'single',
  29900,
  1,
  1,
  5,
  100,
  3,
  true,
  true,
  false,
  true,
  true,
  true,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false
),

(
  'school',
  'School',
  'single',
  49900,
  1,
  1,
  null,
  null,
  null,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false
),

(
  'group_starter',
  'Group Starter',
  'group',
  69900,
  2,
  3,
  null,
  null,
  null,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  false,
  false,
  false,
  false,
  false,
  false,
  false
),

(
  'group_pro',
  'Group Pro',
  'group',
  99900,
  4,
  6,
  null,
  null,
  null,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  false,
  false,
  false,
  false
),

(
  'group_elite',
  'Group Elite',
  'group',
  149900,
  7,
  10,
  null,
  null,
  null,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true
),

(
  'enterprise',
  'Enterprise',
  'enterprise',
  null,
  11,
  null,
  null,
  null,
  null,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true
)

on conflict (code) do update
set
  name = excluded.name,
  plan_type = excluded.plan_type,
  monthly_price_cents = excluded.monthly_price_cents,
  min_schools = excluded.min_schools,
  max_schools = excluded.max_schools,
  max_teachers = excluded.max_teachers,
  max_learners = excluded.max_learners,
  report_history_months = excluded.report_history_months,
  whatsapp_delivery = excluded.whatsapp_delivery,
  photo_moments = excluded.photo_moments,
  video_moments = excluded.video_moments,
  awards = excluded.awards,
  try_at_home = excluded.try_at_home,
  reaction_tracking = excluded.reaction_tracking,
  full_report_history = excluded.full_report_history,
  priority_support = excluded.priority_support,
  white_label = excluded.white_label,
  custom_onboarding = excluded.custom_onboarding,
  central_group_dashboard = excluded.central_group_dashboard,
  cross_branch_reporting = excluded.cross_branch_reporting,
  group_announcements = excluded.group_announcements,
  dedicated_onboarding = excluded.dedicated_onboarding,
  custom_domain = excluded.custom_domain,
  dedicated_account_manager = excluded.dedicated_account_manager,
  monthly_check_in = excluded.monthly_check_in,
  early_access = excluded.early_access,
  updated_at = now();

alter table public.school_plans
  enable row level security;
